# Security
spring:
  security:
    user:
      name: admin
      password: admin

# Postgresql
app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/bookstore
      username: root
      password: 1
      pool-size: 30

springdoc:
  api-docs:
    path: /api-docs

# Server
server:
  port: 3001
