# Security
spring:
  security:
    user:
      name: admin
      password: admin

# Jwt
jwt:
  secret: 2F413F442A472D4B6150645367566B59703373367639792442264529482B4D62

# Postgresql
app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/shop_pet
      username: root
      password: 1
      pool-size: 30

springdoc:
  api-docs:
    path: /api-docs

# Server
server:
  port: 3001
