# Security
# spring:
#   security:
#     user:
#       name: admin
#       password: admin

# Jwt
jwt:
  secret: 2F413F442A472D4B6150645367566B59703373367639792442264529482B4D62

# Google Maps api keys
google:
  api:
    key: AIzaSyAjFS3c_q0ub5-ziyV4jXzdknmpNPa4bDk

# Paypal
paypal:
  mode: sandbox
  client:
    id: AZSoHjXvJB74zwxFzE0zV0V54guze1P2nHLB3oAoDmcZa4hxpbqzCCRSLNngHKuDWHzfRAzk-GKPgSPJ
    secret: EBoH21wKvtcjNjjY45PhiFIdaKHY2PEz7HlMgQM3Gl3Dn8lCFW-7pahbe-Ycu-OUvpzZ7nrt1k9tzJxj

# Postgresql
app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://tiny.db.elephantsql.com/igpakgza
      username: igpakgza
      password: Aq1wvODnX6LBSsDGyi1xY4l4uHGF9Fb7
      pool-size: 30

# app:
#   datasource:
#     main:
#       driver-class-name: org.postgresql.Driver
#       jdbc-url: jdbc:postgresql://localhost:5432/shop_pet
#       username: root
#       password: 1
#       pool-size: 30

springdoc:
  api-docs:
    path: /api-docs

# Server
server:
  port: 3001
